### PR TITLE
Improve performance of pretty-format

### PR DESCRIPTION
**Pull request by thejameskyle**
This doesn't support everything yet, but it is a pretty big restructuring that will allow it to work much much faster.

See comparison: https://gist.github.com/thejameskyle/fce69285d4682923061bf5f83461cc7b

cc @cpojer

### CODE REVIEW

**Comment by cpojer** [comment]
Nice work!

**Comment by thejameskyle** [comment]
Hmm– testing with [really large objects](https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json) this is actually quite a bit slower.

**Comment by thejameskyle** [comment]
Never mind, I realized I've been doing something stupid and measuring this completely wrong. Here is the corrected comparison: https://gist.github.com/thejameskyle/f8b50bf559360549326b52f3bb323d5d

**Comment by cpojer** [comment]
Not sure I can trust you again after this.

**Comment by thejameskyle** [comment]
> Not sure I can trust you again after this.

Hey I improved the performance without even having real metrics to guide me. That must count for something

**Comment by thejameskyle** [comment]
Okay, got everything working again and here are the new perf results: https://gist.github.com/thejameskyle/2b04ffe4941aafa8f970de077843a8fd

**Comment by cpojer** [comment]
I love it. Fantastic work, @thejameskyle.

**Comment by jdalton** [comment]
Woot!

Heads up! There is some handy `process.binding('util')` helpers for `isTypedArray`, `isMap`, `isSet`, etc. that are ~2x that of traditional `Object.prototype.toString.call` checks (Lodash will start using them). Also engines have made `Array.isArray` pretty fast.

**Comment by thejameskyle** [comment]
nice, thanks

**Comment by jdalton** [comment]
No prob. I've [opened an issue on Node](https://github.com/nodejs/node/issues/7196) to expose more of them ⚡

**Pull request merged**
